---
metadata:
  title: "My Awesome Podcast"
  description: "A podcast about technology & programming."
  link: "https://example.com/podcast" # Fallback link
  rss_feed_url: "https://example.com/podcast/feed.xml"
  language: "en-us"
  email: "podcast@example.com"
  author: "Podcast Host"
  category: "Technology"
  image: "https://example.com/podcast/images/podcast_cover.png" # Fallback image
  explicit: false
  use_asset_hash_as_guid: false # Default: Use asset_url. Set to true to use content hash (SHA256/MD5/ETag).
  copyright: "© 2024 Your Name/Company" # Optional copyright notice
  # --- Podcast Standards Project Recommended Tags --- #
  podcast_locked: "no" # "yes" or "no". Prevents feed import by other platforms without owner confirmation (uses email above).
  # podcast_guid: "YOUR-PODCAST-GUID-HERE" # A unique, permanent ID for the entire podcast (UUID recommended).
                                            # If omitted, a GUID will be generated based on rss_feed_url.
                                            # Generate one using: python -c "import uuid; print(uuid.uuid4())" or an online generator.
                                            # Example: 9b024349-ccf0-5f69-a609-6b82873eab3c

episodes:
  - title: "Episode 1: The Beginning"
    description: "Introduction to the podcast."
    publication_date: "2023-01-15T10:00:00Z"
    asset_url: "https://example.com/podcast/episodes/episode1.mp3"
    episode: 1
    season: 1
    episode_type: "full"
    # This episode will use the global link and image from metadata
    transcripts:
      - url: "https://example.com/podcast/transcripts/episode1.srt"
        type: "application/x-subrip"
      - url: "https://example.com/podcast/transcripts/episode1.vtt"
        type: "text/vtt"
        language: "en" # Optional: Language code (e.g., "en", "en-US", "es"). Follows RFC 5646.

  - title: "Episode 2: Deep Dive into Python"
    description: "Exploring advanced Python features & common pitfalls."
    publication_date: "2023-01-22T10:00:00Z"
    asset_url: "https://example.com/podcast/episodes/episode2.mp3"
    link: "https://example.com/podcast/episodes/2" # Episode-specific link
    image: "https://example.com/podcast/images/episode2_cover.png" # Episode-specific image
    episode: 2
    season: 1
    episode_type: "full"
    # This episode has specific link/image but no transcripts

  - title: "Special Bonus Episode"
    description: "An interview with a special guest."
    publication_date: "2023-01-25T12:00:00Z"
    asset_url: "https://example.com/podcast/episodes/bonus1.mp3"
    link: "https://example.com/podcast/episodes/bonus" # Episode-specific link
    # This episode will use the global image from metadata, but has its own link
    episode_type: "bonus"
    transcripts:
      - url: "https://example.com/podcast/transcripts/bonus1.json"
        type: "application/json"
        # language: "es" # Optional: Language code (e.g., "en", "en-US", "es"). Follows RFC 5646.
