---
name: Python Unit Tests and Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.1

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --with dev,test

      - name: Install ffmpeg
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          poetry run ruff check . --select=E9,F63,F7,F82 --show-source

          # check all errors as warnings
          poetry run ruff check . --exit-zero

      - name: Lint YAML files
        run: |
          poetry run yamllint -fgithub -d "{rules: {line-length: false}}" podcast_config.example.yaml

      - name: Run tests with coverage
        run: |
          poetry run pytest tests/ --cov=podcast_rss_generator --cov-report=xml

      - name: Check test coverage
        run: |
          poetry run python -c "import sys, xml.etree.ElementTree as ET; root = ET.parse('coverage.xml').getroot(); coverage = float(root.get('line-rate')) * 100; print(f'Test coverage: {coverage:.2f}%'); sys.exit(0 if coverage >= 80 else 1)"
